version: '3'
services:
  mobilebuilder:
    container_name: dev_react
    build: .
    volumes:
      - ./wakey_wakey:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 8081:8081
