version: '3'

services:
    wakey:
        container_name: ${WAKEY_CONTAINER_NAME}
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${WAKEY_PATH}:/app/
        ports:
            - "${WAKEY_PATH_PORT}:80"
        env_file:
            - .env


